### ISSUE TITLE
wallet id error !!

### ISSUE THREAD

**Issue by evilcode1** [Atrides/xmr-proxy#4]
i still get this error \

2017-06-09 07:12:31,398 DEBUG proxy logger.get_logger # Logging initialized
2017-06-09 07:12:31,398 ERROR proxy xmr-proxy.<module> # Wrong PAYMENT_ID or WALLET !!!

any help please ??

**Comment by Atrides** [comment]
Which length of wallet do you have? If new from poloniex then check it must be without payment_id.
In file xmr-proxy.py string 13 has all options of possible wallets:
` if (settings.PAYMENT_ID and len(settings.PAYMENT_ID)!=64) or len(settings.WALLET)!=95 or len(settings.WALLET)!=106:`

**Comment by evilcode1** [comment]
im using mymonero wallet , which is 95 letter , i use it without payment id becuase i will put the blanace direct not to exchanger

**Comment by evilcode1** [comment]
are u still there ??

**Comment by Atrides** [comment]
Then check your wallet in config file again. This line check the length of wallet and here is 95 presented.

**Comment by WoK-E** [comment]
You need to use AND for your conditions, not OR

**Comment by evilcode1** [comment]
i need to solve my problem guys !!! i did not understand what Atrides said !!

**Comment by evilcode1** [comment]
@WoK-E are u sure it's work if i changed or to and here : 
`if __name__ == '__main__':
    if (settings.PAYMENT_ID and len(settings.PAYMENT_ID)!=64) and len(settings.WALLET)!=95 or len(settings.WALLET)!=106:
        log.error("Wrong PAYMENT_ID or WALLET !!!")
        quit()`
i got this ?? 
https://s11.postimg.org/k4j4r9k1v/Screen_Shot_2017-06-10_at_6.00.26_AM.png

**Comment by evilcode1** [comment]
@WoK-E  when i change the code it's working for 2 mint's and then i got this damn error : 

> C:\Python27\lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\internet\selectreactor.py:151:_doReadOrWrite
C:\Python27\lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\internet\tcp.py:215:doRead
C:\Python27\lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\internet\tcp.py:221:_dataReceived
C:\Users\Administrator\Desktop\xmr-proxy-master\stratum\protocol.py:194:dataReceived
--- <exception caught here> ---
C:\Users\Administrator\Desktop\xmr-proxy-master\stratum\protocol.py:240:lineReceived
C:\Users\Administrator\Desktop\xmr-proxy-master\stratum\event_handler.py:7:_handle_event
C:\Users\Administrator\Desktop\xmr-proxy-master\mining_libs\client_service.py:45:handle_event
]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xmr-proxy-master\stratum\protocol.py", line 240, in lineReceived
    result = self.event_handler._handle_event(msg_method, msg_params, connection_ref=self)
  File "C:\Users\Administrator\Desktop\xmr-proxy-master\stratum\event_handler.py", line 7, in _handle_event
    return defer.maybeDeferred(wrap_result_object, self.handle_event(msg_method, msg_params, connection_ref))
  File "C:\Users\Administrator\Desktop\xmr-proxy-master\mining_libs\client_service.py", line 45, in handle_event
    (blob, job_id, target, user_id) = params["blob"],params["job_id"],params["target"],params["id"]
KeyError: 'id'

>

**Comment by WoK-E** [comment]
Change line 13 as follows:
if (settings.PAYMENT_ID and len(settings.PAYMENT_ID)!=64) **and** len(settings.WALLET)!=95 **and** len(settings.WALLET)!=106:

@evilcode1 the error has nothing to do with this change. I use dwarfpool and have about 20 miners connecting to it via the proxy with no issues

**Comment by evilcode1** [comment]
Okay man this issue is solved by modify the code , thanx
