### ISSUE TITLE
Proxy is freez after 500 client 

### ISSUE THREAD

**Issue by evilcode1** [Atrides/xmr-proxy#5]
Hello dear,,,,
I used proxy on my rdp ,,, its work ok till the clients become 500+ the cmd screen freezed and the minning speed is 0kh on ur pool is there any limtaion or what is the problem

**Comment by evilcode1** [comment]
are u there ?????????? please response

**Comment by evilcode1** [comment]
hello ????????? are y there I need to solve this problem !!

**Comment by evilcode1** [comment]
I still have the problem anyhelp here !!

**Comment by evilcode1** [comment]
where is the damn tool dev. why he did not response ????????????????????????????????????????????????????????????????????????????????????

**Comment by Atrides** [comment]
Proxy has limit to 65535 sessions. Your 500 connections are limited by your system.

Change settings in /etc/security/limits.conf

proxyuser hard nofile 1048576
proxyuser soft nofile 1048576
