### ISSUE TITLE
Always complaint about wrong wallet id or address

### ISSUE THREAD

**Issue by skygunner** [Atrides/xmr-proxy#7]
When using either a private wallet address or Kraken address

**Comment by MircoBlitz** [comment]
To help with that,
exchange in xmr-proxy.py line 13:

#WRONG
if (settings.PAYMENT_ID and len(settings.PAYMENT_ID)!=64) or len(settings.WALLET)!=95 or len(settings.WALLET)!=106:

#RIGHT
if (settings.PAYMENT_ID and len(settings.PAYMENT_ID)!=64) or (len(settings.WALLET)!=95 and len(settings.WALLET)!=106):

**Comment by Atrides** [comment]
Fixed, thank you
